Update patch set 3
Patch Set 3:

> > Doesn't look like it worked :[
 > >
 > > I don't see any of the custom actions on the Polygerrit side, but
 > > they're there on the GWT side
 > 
 > automerger install failed: TypeError: self.deprecated.install is
 > not a function
 > Gerrit.install @ gr-app.js:2428
 > (anonymous) @ automerger.js:17

I forgot to update Gerrit to latest master -_-

After I did, the action showed up, but failed to run correctly.

Installing deprecated APIs is deprecated!
gr-app.js:2432 plugin.deprecated.onAction() is deprecated, use plugin.changeActions() instead!
onAction @ gr-app.js:2432
(anonymous) @ automerger.js:95
Gerrit.install @ gr-app.js:2434
(anonymous) @ automerger.js:17
gr-app.js:2434 automerger install failed: TypeError: Gerrit.on is not a function

Is there documentation somewhere about what's NOT deprecated?

Patch-set: 3
Reviewer: Stephen Li <1019952@173816e5-2b9a-37c3-8a2e-48639d4f1153>