Update patch set 3
Patch Set 3: Code-Review-1

> gr-app.js:2434 automerger install failed: TypeError: Gerrit.on is not a function

Thanks for testing. Does 'self.on' work better?

> Is there documentation somewhere about what's NOT deprecated?

For the moment, using deprecated things is okay (since this plugin is designed to work in both the old and new UIs).

Patch-set: 3
Reviewer: Gerrit User 1011842 <1011842@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1