Update patch set 1
Patch Set 1: Verified+1 Code-Review+2

> Patch Set 1: -Code-Review
> 
> Hm. I'm not actually able to get the tests to run when it's changed. I've checkout out stable-2.14 on both gerrit and plugins/automerger.
> Will keep trying for a bit to see if I can figure out what's wrong.
> 
> ERROR: /usr/local/google/home/stephenli/gerrit/plugins/automerger/BUILD:19:1: no such package '@commons-net//jar': The repository could not be resolved and referenced by '//plugins/automerger:automerger_tests'
> ERROR: Analysis of target '//plugins/automerger:automerger_tests' failed; build aborted: no such package '@commons-net//jar': The repository could not be resolved
> INFO: Elapsed time: 0.296s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> FAILED: Build did NOT complete successfully (0 packages loaded)

I checked out stable-2.14 but forgot to pull it -_- so my lib/commons/BUILD file was out of date.

Okay, tests pass and it can build.

Patch-set: 1
Reviewer: Gerrit User 1019952 <1019952@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=+1
Label: Code-Review=+2