Update patch set 8
Patch Set 8:

> > Aw, snap, you're right.
 > > Looks like we need to do more scaffolding for old plugins...
 > >
 > > This one adds Gerrit.post() (and others) to streamline the
 > > migration.
 > > Also, new REST API helper interface for PG-only plugins.
 > > https://gerrit-review.googlesource.com/c/gerrit/+/137131
 > 
 > A bit confused; is Gerrit.post supposed to work in this file, or
 > should it be self.post?
 > 
 > If Gerrit.post is supposed to be working, we're getting an error:
 > gr-app.js:2409 TypeError: Gerrit.post is not a function
 > at getDownstreamConfigMap (automerger.js:78)
 > at onShowChange (automerger.js:88)
 > at HTMLElement._handleShowChange (gr-app.js:2409)
 > at gr-app.js:2406
 > at <anonymous>
 > 
 > If it's supposed to be self.post, we're getting a different error,
 > that happens after we attempt to click the "Recreate automerges"
 > button, where the path appears to be incorrect:
 > 
 > gr-app.js:1748 POST http://localhost:8080/automerger~automerge-change
 > 404 (Not Found)

Ah, I forgot to stop and restart Gerrit.

We're actually getting a DIFFERENT error now. Progress! :D

gr-app.js:1757 POST http://localhost:8080/plugins/automerger/changes/110/revisions/eb6e0720c84e039924e5f8f31533f52c5c81b676/automerger~config-downstream 405 (Method Not Allowed)

gr-app.js:2379 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at addCheckboxes (automerger.js:25)
    at onAutomergeChange (automerger.js:20)
    at HTMLElement.<anonymous> (gr-app.js:2440)

Patch-set: 8
Reviewer: Stephen Li <1019952@173816e5-2b9a-37c3-8a2e-48639d4f1153>