Update patch set 1
Patch Set 1:

Untested, since my uninformed attempt at testing didn't work:

 $ bazel test plugins/automerger/...
 ERROR: /home/jrn/src/gerrit/plugins/automerger/BUILD:4:1: no such package '@re2j//jar': error loading package 'external': The repository named 're2j' could not be resolved and referenced by '//plugins/automerger:automerger__plugin'.
 ERROR: Analysis of target '//plugins/automerger:automerger_tests' failed; build aborted.

Patch-set: 1
Reviewer: Gerrit User 1011842 <1011842@173816e5-2b9a-37c3-8a2e-48639d4f1153>